/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/healthz': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Liveness / readiness probe */
    get: operations['getHealth'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/babies': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List babies */
    get: operations['listBabies'];
    put?: never;
    /** Create a baby */
    post: operations['createBaby'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/babies/{babyId}': {
    parameters: {
      query?: never;
      header?: never;
      path: {
        babyId: components['parameters']['BabyIdParam'];
      };
      cookie?: never;
    };
    /** Get a baby by ID */
    get: operations['getBaby'];
    put?: never;
    post?: never;
    /** Delete a baby (cascade feedings & unlocks) */
    delete: operations['deleteBaby'];
    options?: never;
    head?: never;
    /** Update a baby */
    patch: operations['updateBaby'];
    trace?: never;
  };
  '/foods': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List food items (system + user) */
    get: operations['listFoods'];
    put?: never;
    /** Create a custom food item */
    post: operations['createFood'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/foods/{foodId}': {
    parameters: {
      query?: never;
      header?: never;
      path: {
        foodId: components['parameters']['FoodIdParam'];
      };
      cookie?: never;
    };
    /** Get a food item */
    get: operations['getFood'];
    put?: never;
    post?: never;
    /** Delete a food (system foods cannot be deleted) */
    delete: operations['deleteFood'];
    options?: never;
    head?: never;
    /** Update a food (system foods cannot be edited) */
    patch: operations['updateFood'];
    trace?: never;
  };
  '/babies/{babyId}/feedings': {
    parameters: {
      query?: never;
      header?: never;
      path: {
        babyId: components['parameters']['BabyIdParam'];
      };
      cookie?: never;
    };
    /** List feeding records of a baby */
    get: operations['listFeedings'];
    put?: never;
    /** Create a feeding record */
    post: operations['createFeeding'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/babies/{babyId}/feedings/{feedingId}': {
    parameters: {
      query?: never;
      header?: never;
      path: {
        babyId: components['parameters']['BabyIdParam'];
        feedingId: components['parameters']['FeedingIdParam'];
      };
      cookie?: never;
    };
    /** Get a feeding record */
    get: operations['getFeeding'];
    put?: never;
    post?: never;
    /** Delete a feeding record */
    delete: operations['deleteFeeding'];
    options?: never;
    head?: never;
    /** Update a feeding record */
    patch: operations['updateFeeding'];
    trace?: never;
  };
  '/babies/{babyId}/feedings:import': {
    parameters: {
      query?: never;
      header?: never;
      path: {
        babyId: components['parameters']['BabyIdParam'];
      };
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Batch import feeding records from CSV (skip on conflict) */
    post: operations['importFeedingsCsv'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/babies/{babyId}/trials': {
    parameters: {
      query?: never;
      header?: never;
      path: {
        babyId: components['parameters']['BabyIdParam'];
      };
      cookie?: never;
    };
    /** 該寶寶對每種食材的試敏狀態 (從 materialized view 讀取) */
    get: operations['listTrials'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/babies/{babyId}/recommendations': {
    parameters: {
      query?: never;
      header?: never;
      path: {
        babyId: components['parameters']['BabyIdParam'];
      };
      cookie?: never;
    };
    /** 建議下一個嘗試的食材（低敏優先 + 多元類別） */
    get: operations['getRecommendations'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/achievements': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** 列出所有徽章定義 */
    get: operations['listAchievements'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/babies/{babyId}/achievements': {
    parameters: {
      query?: never;
      header?: never;
      path: {
        babyId: components['parameters']['BabyIdParam'];
      };
      cookie?: never;
    };
    /** 該寶寶已解鎖徽章與所有徽章狀態 */
    get: operations['listBabyAchievements'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/babies/{babyId}/dashboard': {
    parameters: {
      query?: never;
      header?: never;
      path: {
        babyId: components['parameters']['BabyIdParam'];
      };
      cookie?: never;
    };
    /** 首頁總覽（狀態計數 + 最近徽章 + 推薦） */
    get: operations['getDashboard'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/babies/{babyId}/progress': {
    parameters: {
      query?: never;
      header?: never;
      path: {
        babyId: components['parameters']['BabyIdParam'];
      };
      cookie?: never;
    };
    /** 試敏破關進度（unlocked / total，可分 category） */
    get: operations['getProgress'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    /** @enum {string} */
    FoodCategory:
      | 'VEGETABLE'
      | 'MUSHROOM'
      | 'FRUIT'
      | 'SEAFOOD'
      | 'MEAT'
      | 'EGG'
      | 'DAIRY'
      | 'GRAIN'
      | 'NUT'
      | 'OTHER';
    /**
     * @description 低敏 / 中敏 / 高敏
     * @enum {string}
     */
    AllergyRisk: 'LOW' | 'MEDIUM' | 'HIGH';
    /** @enum {string} */
    Reaction: 'NONE' | 'MILD' | 'SEVERE';
    /** @enum {string} */
    TrialStatus: 'UNTRIED' | 'TRYING' | 'UNLOCKED' | 'ALLERGIC';
    PaginationMeta: {
      nextCursor?: string | null;
      total?: number;
    };
    Health: {
      /** @enum {string} */
      status: 'ok';
      /** @enum {string} */
      db: 'ok' | 'down';
      version: string;
    };
    Baby: {
      /** Format: uuid */
      id: string;
      name: string;
      /** Format: date */
      birthDate: string;
      /** @description 動態計算 */
      ageMonth: number;
      avatarColor: string;
      /** Format: date-time */
      createdAt: string;
      /** Format: date-time */
      updatedAt?: string;
    };
    BabyCreate: {
      name: string;
      /** Format: date */
      birthDate: string;
      avatarColor?: string;
    };
    BabyUpdate: {
      name?: string;
      /** Format: date */
      birthDate?: string;
      avatarColor?: string;
    };
    BabyListResponse: {
      data?: components['schemas']['Baby'][];
      meta?: components['schemas']['PaginationMeta'];
    };
    FoodItem: {
      /** Format: uuid */
      id: string;
      name: string;
      category: components['schemas']['FoodCategory'];
      allergyRisk: components['schemas']['AllergyRisk'];
      isSystem: boolean;
      /** Format: date-time */
      createdAt: string;
      /** Format: date-time */
      updatedAt?: string;
    };
    FoodCreate: {
      name: string;
      category: components['schemas']['FoodCategory'];
      allergyRisk: components['schemas']['AllergyRisk'];
    };
    FoodUpdate: {
      name?: string;
      category?: components['schemas']['FoodCategory'];
      allergyRisk?: components['schemas']['AllergyRisk'];
    };
    FoodListResponse: {
      data?: components['schemas']['FoodItem'][];
      meta?: components['schemas']['PaginationMeta'];
    };
    FeedingRecord: {
      /** Format: uuid */
      id: string;
      /** Format: uuid */
      babyId: string;
      /** Format: uuid */
      foodId: string;
      /** @description 由後端 inline 展開 */
      food?: components['schemas']['FoodItem'];
      /** Format: date-time */
      fedAt: string;
      amountMl: number;
      attemptCount: number;
      reaction: components['schemas']['Reaction'];
      note?: string | null;
      /** Format: date-time */
      createdAt: string;
    };
    FeedingCreate: {
      /** Format: uuid */
      foodId: string;
      /** Format: date-time */
      fedAt: string;
      amountMl: number;
      /** @default NONE */
      reaction: components['schemas']['Reaction'];
      note?: string;
    };
    FeedingUpdate: {
      /** Format: date-time */
      fedAt?: string;
      amountMl?: number;
      reaction?: components['schemas']['Reaction'];
      note?: string;
    };
    FeedingListResponse: {
      data?: components['schemas']['FeedingRecord'][];
      meta?: components['schemas']['PaginationMeta'];
    };
    FeedingCreateResponse: {
      feeding: components['schemas']['FeedingRecord'];
      trial?: components['schemas']['TrialState'];
      newlyUnlockedAchievements: components['schemas']['Achievement'][];
    };
    CsvImportResult: {
      /** @description 成功匯入列數 */
      imported: number;
      /** @description 因衝突跳過列數 */
      skipped: number;
      errors: {
        row: number;
        message: string;
        raw?: {
          [key: string]: unknown;
        };
      }[];
    };
    TrialState: {
      /** Format: uuid */
      foodId: string;
      food?: components['schemas']['FoodItem'];
      status: components['schemas']['TrialStatus'];
      attempts: number;
      /** Format: date-time */
      lastFedAt?: string | null;
      hasReaction: boolean;
    };
    Achievement: {
      /** Format: uuid */
      id: string;
      /** @example UNLOCK_10_VEG */
      code: string;
      name: string;
      description: string;
      /** @description 圖示識別碼或 emoji */
      icon: string;
      condition:
        | components['schemas']['CondUnlockCountByCategory']
        | components['schemas']['CondUnlockCountByRisk']
        | components['schemas']['CondFirstFeedingByAge']
        | components['schemas']['CondTotalUnlock'];
    };
    CondUnlockCountByCategory: {
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      type: 'CondUnlockCountByCategory';
      category: components['schemas']['FoodCategory'];
      count: number;
    };
    CondUnlockCountByRisk: {
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      type: 'CondUnlockCountByRisk';
      risk: components['schemas']['AllergyRisk'];
      count: number;
    };
    CondFirstFeedingByAge: {
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      type: 'CondFirstFeedingByAge';
      ageMonth: number;
    };
    CondTotalUnlock: {
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      type: 'CondTotalUnlock';
      count: number;
    };
    BabyAchievement: {
      achievement: components['schemas']['Achievement'];
      unlocked: boolean;
      /** Format: date-time */
      unlockedAt?: string | null;
      /** @description 進度提示 (依條件型別不同欄位) */
      progress?: {
        current?: number;
        target?: number;
      };
    };
    Dashboard: {
      baby: components['schemas']['Baby'];
      statusCounts: {
        UNTRIED?: number;
        TRYING?: number;
        UNLOCKED?: number;
        ALLERGIC?: number;
      };
      progress: components['schemas']['Progress'];
      recentUnlocks: components['schemas']['BabyAchievement'][];
      recommendations: components['schemas']['FoodItem'][];
    };
    Progress: {
      unlocked: number;
      total: number;
      /** Format: float */
      percent: number;
      byCategory: {
        category: components['schemas']['FoodCategory'];
        unlocked: number;
        total: number;
      }[];
    };
    Problem: {
      /** Format: uri */
      type: string;
      title: string;
      status: number;
      detail?: string;
      /** Format: uri */
      instance?: string;
    };
    ValidationProblem: components['schemas']['Problem'] & {
      errors?: {
        path: string;
        message: string;
      }[];
    };
  };
  responses: {
    /** @description Resource not found */
    NotFound: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        'application/problem+json': components['schemas']['Problem'];
      };
    };
    /** @description Validation failed */
    ValidationError: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        'application/problem+json': components['schemas']['ValidationProblem'];
      };
    };
    /** @description Unexpected server error */
    InternalError: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        'application/problem+json': components['schemas']['Problem'];
      };
    };
  };
  parameters: {
    BabyIdParam: string;
    FoodIdParam: string;
    FeedingIdParam: string;
    /** @description 由上一頁回應 meta.nextCursor 取得 */
    CursorParam: string;
    LimitParam: number;
  };
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  getHealth: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description API up & DB reachable */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Health'];
        };
      };
    };
  };
  listBabies: {
    parameters: {
      query?: {
        /** @description 由上一頁回應 meta.nextCursor 取得 */
        cursor?: components['parameters']['CursorParam'];
        limit?: components['parameters']['LimitParam'];
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description A list of babies */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['BabyListResponse'];
        };
      };
      500: components['responses']['InternalError'];
    };
  };
  createBaby: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['BabyCreate'];
      };
    };
    responses: {
      /** @description Baby created */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Baby'];
        };
      };
      422: components['responses']['ValidationError'];
    };
  };
  getBaby: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        babyId: components['parameters']['BabyIdParam'];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Baby */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Baby'];
        };
      };
      404: components['responses']['NotFound'];
    };
  };
  deleteBaby: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        babyId: components['parameters']['BabyIdParam'];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Deleted */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      404: components['responses']['NotFound'];
    };
  };
  updateBaby: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        babyId: components['parameters']['BabyIdParam'];
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['BabyUpdate'];
      };
    };
    responses: {
      /** @description Updated baby */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Baby'];
        };
      };
      404: components['responses']['NotFound'];
      422: components['responses']['ValidationError'];
    };
  };
  listFoods: {
    parameters: {
      query?: {
        category?: components['schemas']['FoodCategory'];
        allergyRisk?: components['schemas']['AllergyRisk'];
        /** @description 名稱模糊搜尋 (icontains) */
        search?: string;
        sort?: 'risk_asc' | 'risk_desc' | 'name_asc' | 'name_desc';
        /** @description 由上一頁回應 meta.nextCursor 取得 */
        cursor?: components['parameters']['CursorParam'];
        limit?: components['parameters']['LimitParam'];
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description List of foods */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['FoodListResponse'];
        };
      };
    };
  };
  createFood: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['FoodCreate'];
      };
    };
    responses: {
      /** @description Food created */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['FoodItem'];
        };
      };
      /** @description Name already exists */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['Problem'];
        };
      };
      422: components['responses']['ValidationError'];
    };
  };
  getFood: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        foodId: components['parameters']['FoodIdParam'];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Food */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['FoodItem'];
        };
      };
      404: components['responses']['NotFound'];
    };
  };
  deleteFood: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        foodId: components['parameters']['FoodIdParam'];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Deleted */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description System food is read-only */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['Problem'];
        };
      };
      404: components['responses']['NotFound'];
      /** @description Food is referenced by feeding records */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['Problem'];
        };
      };
    };
  };
  updateFood: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        foodId: components['parameters']['FoodIdParam'];
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['FoodUpdate'];
      };
    };
    responses: {
      /** @description Updated food */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['FoodItem'];
        };
      };
      /** @description System food is read-only */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['Problem'];
        };
      };
      404: components['responses']['NotFound'];
      422: components['responses']['ValidationError'];
    };
  };
  listFeedings: {
    parameters: {
      query?: {
        /** @description 將 from/to 自動套用為當週或當月區間 */
        view?: 'week' | 'month';
        from?: string;
        to?: string;
        foodId?: string;
        reaction?: components['schemas']['Reaction'];
        /** @description 由上一頁回應 meta.nextCursor 取得 */
        cursor?: components['parameters']['CursorParam'];
        limit?: components['parameters']['LimitParam'];
      };
      header?: never;
      path: {
        babyId: components['parameters']['BabyIdParam'];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Feedings */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['FeedingListResponse'];
        };
      };
      404: components['responses']['NotFound'];
    };
  };
  createFeeding: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        babyId: components['parameters']['BabyIdParam'];
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['FeedingCreate'];
      };
    };
    responses: {
      /** @description Feeding created (含同步解鎖的徽章) */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['FeedingCreateResponse'];
        };
      };
      404: components['responses']['NotFound'];
      /** @description Duplicate (babyId, foodId, fedAt) */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['Problem'];
        };
      };
      422: components['responses']['ValidationError'];
    };
  };
  getFeeding: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        babyId: components['parameters']['BabyIdParam'];
        feedingId: components['parameters']['FeedingIdParam'];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Feeding */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['FeedingRecord'];
        };
      };
      404: components['responses']['NotFound'];
    };
  };
  deleteFeeding: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        babyId: components['parameters']['BabyIdParam'];
        feedingId: components['parameters']['FeedingIdParam'];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Deleted */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      404: components['responses']['NotFound'];
    };
  };
  updateFeeding: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        babyId: components['parameters']['BabyIdParam'];
        feedingId: components['parameters']['FeedingIdParam'];
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['FeedingUpdate'];
      };
    };
    responses: {
      /** @description Updated feeding */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['FeedingRecord'];
        };
      };
      404: components['responses']['NotFound'];
      422: components['responses']['ValidationError'];
    };
  };
  importFeedingsCsv: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        babyId: components['parameters']['BabyIdParam'];
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'multipart/form-data': {
          /**
           * Format: binary
           * @description UTF-8 CSV, 標頭：food_name,fed_at,amount_ml,reaction,note
           *     最大 2MB / 5000 列
           */
          file: string;
          /**
           * @description 不寫入資料庫，只回報結果
           * @default false
           */
          dryRun?: boolean;
        };
      };
    };
    responses: {
      /** @description Import summary */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['CsvImportResult'];
        };
      };
      /** @description 檔案格式錯誤 / 超過大小限制 */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['Problem'];
        };
      };
      404: components['responses']['NotFound'];
    };
  };
  listTrials: {
    parameters: {
      query?: {
        status?: components['schemas']['TrialStatus'];
        category?: components['schemas']['FoodCategory'];
      };
      header?: never;
      path: {
        babyId: components['parameters']['BabyIdParam'];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Trial states */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            data?: components['schemas']['TrialState'][];
          };
        };
      };
      404: components['responses']['NotFound'];
    };
  };
  getRecommendations: {
    parameters: {
      query?: {
        limit?: number;
      };
      header?: never;
      path: {
        babyId: components['parameters']['BabyIdParam'];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Recommendations */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            data?: components['schemas']['FoodItem'][];
          };
        };
      };
      404: components['responses']['NotFound'];
    };
  };
  listAchievements: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Achievements */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            data?: components['schemas']['Achievement'][];
          };
        };
      };
    };
  };
  listBabyAchievements: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        babyId: components['parameters']['BabyIdParam'];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Achievement progress per baby */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            data?: components['schemas']['BabyAchievement'][];
          };
        };
      };
      404: components['responses']['NotFound'];
    };
  };
  getDashboard: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        babyId: components['parameters']['BabyIdParam'];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Dashboard payload */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Dashboard'];
        };
      };
      404: components['responses']['NotFound'];
    };
  };
  getProgress: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        babyId: components['parameters']['BabyIdParam'];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Progress */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Progress'];
        };
      };
      404: components['responses']['NotFound'];
    };
  };
}
